name: Build

on:
  push:
    branches: main
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash -l {0}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.1-0'
          environment-file: environment.yml
          cache-environment: true

      - name: Lint
        run: |
          set -eux
          jlpm
          jlpm run build
          jlpm run lint:check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.1-0'
          environment-file: environment.yml
          cache-environment: true

      - name: Build the extension
        run: python -m build

      - uses: actions/upload-artifact@v2
        with:
          name: dist ${{ github.run_number }}
          path: ./dist

  test_isolated:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - uses: actions/download-artifact@v2
        with:
          name: dist ${{ github.run_number }}
          path: ./dist
      - name: Install and Test
        run: |
          set -eux
          # Remove NodeJS, twice to take care of system and locally installed node versions.
          sudo rm -rf $(which node)
          sudo rm -rf $(which node)
          pip install jupyterlite_xeus_python*.tar.gz
          pip install "jupyterlab==4"
          jupyter labextension list 2>&1 | grep -ie "@jupyterlite/xeus-python-kernel.*OK"

          # TODO: add JupyterLite browser check
          # python -m jupyterlab.browser_check --no-chrome-test
        working-directory: dist

  python-tests-mamba-python:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v2
        with:
          name: dist ${{ github.run_number }}
          path: ./dist

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.1-0'
          environment-file: environment.yml
          cache-environment: true

      - name: Make sure the Mamba Python API is available
        run: |
          mamba install mamba
          python -c "from mamba.api import create"

      - name: Install
        run: pip install jupyterlite_xeus_python*.tar.gz
        working-directory: dist

      - name: Run tests
        run: pytest -rP test_xeus_python_env.py
        working-directory: tests

  python-tests-mamba:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v2
        with:
          name: dist ${{ github.run_number }}
          path: ./dist

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.1-0'
          environment-file: environment.yml
          cache-environment: true

      - name: Install
        run: pip install jupyterlite_xeus_python*.tar.gz
        working-directory: dist

      - name: Run tests
        run: pytest -rP test_xeus_python_env.py
        working-directory: tests

  python-tests-micromamba:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v2
        with:
          name: dist ${{ github.run_number }}
          path: ./dist

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.1-0'
          environment-file: environment.yml
          cache-environment: true

      - name: Install
        run: pip install jupyterlite_xeus_python*.tar.gz
        working-directory: dist

      - name: Run tests
        run: pytest -rP test_xeus_python_env.py
        working-directory: tests

  python-tests-conda:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v2
        with:
          name: dist ${{ github.run_number }}
          path: ./dist

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.1-0'
          environment-file: environment.yml
          cache-environment: true

      - name: Install
        run: pip install jupyterlite_xeus_python*.tar.gz
        working-directory: dist

      - name: Run tests
        run: pytest -rP test_xeus_python_env.py
        working-directory: tests
