language: cpp
env:
  global:
    - MINCONDA_VERSION="latest"
    - MINCONDA_LINUX="Linux-x86_64"
    - MINCONDA_OSX="MacOSX-x86_64"
matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      env: PY=3
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      env: PY=2
    - os: osx
      osx_image: xcode8
      compiler: clang
      env: PY=3
install:
    # Define the version of miniconda to download
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        MINCONDA_OS=$MINCONDA_LINUX;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        MINCONDA_OS=$MINCONDA_OSX;
      fi
    - if [[ "$PY" == "3" ]]; then
          wget "http://repo.continuum.io/miniconda/Miniconda3-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh;
      else
          wget "http://repo.continuum.io/miniconda/Miniconda2-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Host dependencies
    - conda install xeus=0.20.0 nlohmann_json cppzmq xtl pybind11=2.2.4 jedi=0.13.1 pygments=2.3.1 -c conda-forge
    # Build dependencies
    - conda install cmake -c conda-forge
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        conda install gxx_linux-64 libgcc -c conda-forge;
      fi
    # Test dependencies
    # jupyter_kernel_test is Python3 only.
    # With Python2, we first create a Python3 environment for jupyter_kernel_test
    - if [[ "$PY" == "3" ]]; then
        conda install pytest jupyter_kernel_test -c conda-forge;
      else
        conda create --name=kernel_test python=3 pytest jupyter_kernel_test -c conda-forge;
        source activate kernel_test;
      fi
    # Activate root environment
    - source activate root
    # For debugging
    - which python
    - python --version
    # Build and install xeus-python
    - mkdir build
    - cd build
    - cmake -D CMAKE_INSTALL_PREFIX=$HOME/miniconda -D DOWNLOAD_GTEST=ON -D PYTHON_EXECUTABLE=`which python` -D XEUS_PYTHON_HOME="$HOME/miniconda" -D CMAKE_INSTALL_LIBDIR=lib -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
    - make -j2 install
script:
    # For Python 2, activate the kernel_test Python3 environment
    - if [[ "$PY" == "2" ]]; then
        source activate kernel_test;
        jupyter kernelspec install --sys-prefix ../share/jupyter/kernels/xpython;
      fi
    - cd test
    - ./test_xeus_python
    - cd ../../test && py.test .
