name: xeus-python
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  - ninja
  # Host dependencies
  - xeus>=5.0.0
  - xeus-zmq>=3.0,<4.0
  - nlohmann_json=3.11.3
  - pybind11>=2.6.1,<3.0
  - pybind11_json>=0.2.6,<0.3
  - xeus-python-shell>=0.6.3,<0.7
  - debugpy>=1.6.5
  # Test dependencies
  - pytest
  - nbval
  - ipympl
  - jupyter_kernel_test<0.8
  - doctest
  - pluggy=1.3
