name: xeus-python
channels:
  - conda-forge
dependencies:
  # Builde dependencies
  - cmake
  # Host dependencies
  - xeus=1.0.0
  - nlohmann_json
  - cppzmq
  - xtl=0.7.0
  - jedi=0.18.0
  - pybind11=2.6.0
  - pybind11_json=0.2.6
  - pygments
  - ipython=7.14.0
  - debugpy
  # Test dependencies
  - jupyter_kernel_test
