name: xeus-python-wasm-host
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - python
  - ipython
  - pybind11
  - jedi
  - xtl
  - nlohmann_json
  - pybind11_json
  - numpy
  - xeus-lite
  - xeus 
  - xeus-python-shell>=0.5
  - pyjs>=0.7.0,<0.8
  - wasm_requests>=0.1.5
