name: xeus-python-wasm-host
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - ipython
  - pybind11
  - jedi
  - nlohmann_json
  - pybind11_json
  - numpy
  - xeus-lite
  - xeus
  - xeus-python-shell>=0.6.3
  - pyjs >=2,<3
  - requests-wasm-polyfill>=0.3.0
  - libpython
  - zstd
