name: xeus-python
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  - ninja
  - cmake < 4  # TODO: remove pin on CMake
  # Host dependencies
  - xeus-zmq>=3.1,<4.0
  - nlohmann_json=3.12.0
  - pybind11>=2.6.1,<3.0
  - pybind11_json>=0.2.6,<0.3
  # The debugger is not available with python 3.13 because
  # of a spurious bug in debugpy
  - python <3.13
  #- xeus-python-shell>=0.6.3,<0.7 # we need an unreleased version
  - debugpy>=1.6.5
  - libuvw
  - ipython
  # Test dependencies
  - pytest
  - nbval
  - ipympl
  - jupyter_kernel_test<0.8
  - doctest
  - pluggy=1.3
