name: xeus-python-kernel-docs

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - click
  - typer
  - pydata-sphinx-theme
  - yarn
  - jupyterlab
  - empack>=2.0.3
  - pip:
    - jupyterlite==0.1.0b17
    - jupyterlite-sphinx
    - ..
