name: xeus-python-kernel
channels:
  - conda-forge
  - conda-forge/label/jupyterlite_core_alpha
dependencies:
  - python
  - pip
  - jupyterlab >=4.0,<5
  - jupyterlite-core >=0.2.0a1,<0.3.0
  - traitlets
  - requests
  - typer
  - pytest
  - empack >=3,<4
  - nodejs=20
  - mamba
