name: xeus-python-kernel-docs

channels:
  - conda-forge

dependencies:
  - mamba
  - python=3.10
  - pip
  - nodejs=20
  - click
  - typer
  - linkify-it-py
  - myst-parser
  - pydata-sphinx-theme
  - jupyterlab >=4.0.5,<5
  - jupyterlite-core
  - jupyterlite-sphinx
  - jupyterlite-xeus
