name: xeus-python-kernel-docs
channels:
  - https://prefix.dev/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - numpy
  - matplotlib
  - pillow
  - ipywidgets
  - pip:
    - ipycanvas
